= AsciiSpec Package for SublimeText 3
:experimental: true 

image:https://travis-ci.org/bsmith-n4/asciispec-sublime.svg?branch=master["Build Status", link="https://travis-ci.org/bsmith-n4/asciispec-sublime"]

This package provides more complete and up-to-date syntax highlighting, snippets and other goodies for AsciiDoc editing in http://www.sublimetext.com/3[SublimeText 3].

== Snippets

[cols="h,a"]
|===
| Name               | Trigger   

| Button             | btn kbd:[Tab]         
| Comment Block      | ++//++ kbd:[Tab]          
| Document Title     | h0 kbd:[Tab]          
| Example Block      | ++==++ kbd:[Tab]          
| Footnote Reference | fnr kbd:[Tab]         
| Footnote           | fn kbd:[Tab]          
| Image              | img kbd:[Tab]         
| Keyboard Shortcut  | kbd kbd:[Tab]         
| Listing Block      | -- kbd:[Tab]          
| Passthrough Block  | pass:[++] kbd:[Tab]            
| Quote Block        | __ kbd:[Tab]  
| Requirement Block  | req kbd:[Tab]        
| Section Title 1–5  | h1 kbd:[Tab], …, h5 kbd:[Tab] 
| Sidebar block      | pass:[**] kbd:[Tab]             
| Table              | \|= kbd:[Tab]          
|===

== Keymaps

* Asterisks (strong), underscores (emphasis), backticks (monospaced), English quotation marks, and Czech quotation marks are autopaired and will wrap selected text.
    - If you start an empty pair and hit backspace, both elements are deleted.
    - If you start an empty asterisks pair and hit kbd:[Space] or kbd:[Tab], the right element is deleted (because you probably wanted to start a list, not a strong text).
* At the end of a (un)ordered list item, pressing kbd:[Enter] will automatically insert the new list item “bullet.”
    - Pressing kbd:[Enter] on the blank list item will remove it.
    - Pressing kbd:[Tab] on the blank list item, or selected item(s), will increase nesting level and indent it.
    - Pressing kbd:[Shift] kbd:[Tab] on the blank list item, or selected item(s), will decrease nesting level and unindent it.
    - You can disable indentation of list items in your settings file.
* At the end of a callouts list item, pressing kbd:[Enter] will automatically insert the new list item with incremented number.
    - Pressing kbd:[Enter] on the blank list item will remove it.

== Others

* Displays document and section titles in the local symbol list (kbd:[Ctrl] kbd:[R] / kbd:[Cmd] kbd:[R]) and the global symbol list (kbd:[Ctrl] kbd:[Shift] kbd:[R] / kbd:[Cmd] kbd:[Shift] kbd:[R]).
    - In the local symbol list, titles are nicely indented.
    - In the global symbol list, titles will start with `=`, so you will know they belong to AsciiDoc files at a glance. Also they will be on top of the list because of the presedence of `=`.
* Defines http://docs.sublimetext.info/en/latest/reference/comments.html[comment markers] so you can use http://docs.sublimetext.info/en/latest/reference/comments.html#related-keyboard-shortcuts[default commands] to comment and uncomment lines of text.
* Provides completions for attributes (built-in and locally defined) and cross references (local anchors and titles).

== Installation with Package Control

Prerequisite: http://wbond.net/sublime_packages/package_control[Package Control]

Installing via Package Control will keep this package up-to-date automatically.

Once Package Control is installed, restart Sublime Text.

1. Open the Command Palette (kbd:[Ctrl + Shift + P]
   on Windows and Linux. kbd:[⌘ + ⇧ + P] on OS X).
2. Type "Add" and select "Add Repository".
3. Paste the repository URL https://github.com/bsmith-n4/asciispec-sublime into the form at the bottom of the window.
4. Open the Command Palette, type "Install" and select "Package Control: Install Package".
5. Type "asciispec" and select "asciispec-sublime" from list.
6. A restart of Sublime Text may be necessary to initialize the plugin.

== Manual Installation

Install this plugin manually from GitHub:

1. Go to your Packages subdirectory under the ST3’s data directory:
    * OS X: `pass:[~]/Library/Application\ Support/Sublime\ Text\ 3/Packages/`
    * Linux: `pass:[~]/.config/sublime-text-3/Packages/`
    * Windows: `pass:[%APPDATA%]\Sublime Text 3\Packages\`
2. Clone this repository here into subdirectory asciispec-sublimetext:

 git clone https://github.com/bsmith-n4/asciispec-sublime.git 

3. Restart SublimeText.

== Acknowledgement

The syntax definition is based on https://github.com/mattneub/AsciiDoc-TextMate-2.tmbundle[AsciiDoc-TextMate-2.tmbundle] by https://github.com/mattneub[Matt Neuburg].

Most of the commands, keymaps and some text in this readme are based on (or inspired by) https://github.com/SublimeText-Markdown/MarkdownEditing[MarkdownEditing] package.

== Contributing

1. Fork it
2. Create your feature branch (`git checkout -b my-new-feature`)
3. Commit your changes (`git commit -am 'Add some feature'`)
4. Push to the branch (`git push origin my-new-feature`)
5. Create new Pull Request

== License


This project is licensed under http://opensource.org/licenses/MIT/[MIT License]. +
For the full text of the license, see the [LICENSE](LICENSE) file.
